version: "3.7"
services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - nextnetwork
 
  redis:
    image: redis
    hostname: redis
    restart: always
    networks:
      - nextnetwork

  next:
    image: nextcloud
    restart: always
    ports:
      - "8080:80"
    links:
      - db
      - redis
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_HOST=${MARIADB_HOST}
      - REDIS_HOST=${REDIS_HOST}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=nextnetwork"
      - "traefik.http.routers.next.entrypoints=web,websecure"
      - "traefik.http.routers.next.rule=Host(`${NEXTCLOUD_URL}`)"
      - "traefik.http.services.next.loadbalancer.server.port=80"
      - "traefik.http.routers.next.tls=true"
      - "traefik.http.routers.next.tls.certresolver=leresolver"
    networks:
      - nextnetwork
    depends_on:
       - db
       - redis

  traefik:
    restart: unless-stopped
    image: traefik:latest
    ports:
      - "80:80"
      - "8081:8080"
      - "443:443"
    labels:
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

    volumes:
      - /home/dockeruser/traefik/traefik.toml:/traefik.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/dockeruser/traefik/acme.json:/acme.json
    networks:
      - nextnetwork

  reverse-proxy-https-helper:
    image: alpine
    command: sh -c "cd /etc/ssl/traefik
      && wget traefik.me/cert.pem -O cert.pem
      && wget traefik.me/privkey.pem -O privkey.pem"
    volumes:
      - certs:/etc/ssl/traefik
 
networks:
  nextnetwork:
    driver: bridge

volumes:
  mariadb:
  nextcloud:
  certs:
